<?php


/**
 * Implementation of hook_init().
 */
function webfact_init() {
  drupal_add_css(drupal_get_path('module', 'webfact') . '/css/webfact.css',
    array('group' => CSS_DEFAULT, 'every_page' => TRUE));
}


//function webfact_install(){
//}


function webfact_permission() {
  return array(
    'access websites' => array(
      'title' => t('Access websites'),
      'description' => t('Allow users to access website details'),
    ),
    'access templates' => array(
      'title' => t('Access templates'),
      'description' => t('Allow users to access website templates'),
    ),
    'manage containers' => array(
      'title' => t('Manage Containers'),
      'description' => t('Allow user full access to docker containers'),
    ),
  );
}

function webfact_menu() {
  $items['website/%/%'] = array(
    'page callback'    => 'webfact_arguments',
    'page arguments'   => array(0, 1, 2),
    'access arguments' => array('access websites'),
    'type' => MENU_CALLBACK, // no menu
  );

  // admin form in Configuration > Development
  $items['admin/config/development/webfact'] = array(
    'title' => t('Webfactory'),
    'description' => t('Webfactory docker URL and parameters'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('webfact_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );  

  // bootstrap tests
  $items['bob'] = array(   
    'page callback'    => 'webfact_bootstrap',
    'access arguments' => array('access websites'),
    'type' => MENU_CALLBACK, // no menu
  );
  $items['site/%/%'] = array(
    'page callback'    => 'webfact_bootstrap',
    'page arguments'   => array(0, 1, 2),
    'access arguments' => array('access websites'),
    'type' => MENU_CALLBACK, // no menu
  );
  return $items;
}


// admin form
function webfact_admin_settings() {
  $form['webfact_fserver'] = array(
    '#title' => t('Domain prefix'),
    '#default_value' => variable_get('webfact_fserver', array('')),
    '#description' => t('e.g. webfact.example.ch'),
    '#type' => 'textfield',
    '#size' => 30,
    '#maxlength' => 100,
  );
  $form['webfact_dserver'] = array(
    '#title' => t('Docker API URL'),
    '#default_value' => variable_get('webfact_dserver', array('')),
    '#description' => t('e.g. http://dock.example.ch:2375'),
    '#type' => 'textfield',
    '#size' => 30,
    '#maxlength' => 100,
  );
  $form['webfact_cont_image'] = array(
    '#title' => t('Base image for creating containers'),
    '#default_value' => variable_get('webfact_cont_image', array('')),
    '#description' => t('e.g. boran/drupal'),
    '#type' => 'textfield',
    '#size' => 30,
    '#maxlength' => 100,
  );  
  $form['webfact_rproxy'] = array(
    '#title' => t('Reverse proxy container ID'),
    '#default_value' => variable_get('webfact_rproxy', array('')),
    '#description' => t('e.g. nginxproxy'),
    '#type' => 'textfield',
    '#size' => 30,
    '#maxlength' => 100,
  );
  $form['webfact_loglines'] = array(
    '#title' => t('How many lines to tail on logs'),
    '#default_value' => variable_get('webfact_loglines', array('')),
    '#description' => t('e.g. 90'),
    '#type' => 'textfield',
    '#size' => 10,
    '#maxlength' => 100,
  );
  $form['webfact_env_server'] = array(
    '#title' => t('Optional: an environment variable to pass to all containers'),
    '#default_value' => variable_get('webfact_env_server', array('')),
    '#description' => t('To identify where containers were created. e.g. WEBFACT_SERVER=foo.example.ch'),
    '#type' => 'textfield',
    '#size' => 30,
    '#maxlength' => 100,
  );
  return system_settings_form($form);
}


function webfact_theme() {
  return array(
    'bootstrap' => array(
      'template' => 'bootstrap',
    ),
    'webfacts' => array(
      'template' => 'webfacts',
    ),
  );
}

function webfact_bootstrap($path='x', $action='y', $id=0) {
  //dpm('webfact_bootstrap');
  //drupal_set_message($action);
  if (!is_numeric($id)) {      // only numbers: security
    #drupal_access_denied();
    return array('#markup' => '<p>' . t('Error: arguments not valid') . ",
      path=$path, 1=$action, 2=$id" . '</p>');
  }

  return theme('bootstrap');
}


/* 
 * hook for the /website/%/% page 
 */
function webfact_arguments($path, $action, $id) {
  //drupal_set_message($action);
  if (!is_numeric($id)) {      // only numbers: security
    #drupal_access_denied();
    return array('#markup' => '<p>' . t('Error: arguments not valid') . ", 
      path=$path, 1=$action, 2=$id" . '</p>');
  }

  $w= new WebfactController;
  //return $w->helloWorldPage();
  return $w->arguments($action, $id);   // send back render array
}


